travis:
  secure:
    BINSTAR_TOKEN: RqPkDqAvfYrjZzRAlJ8Od5dzVX0A6tZCyiX7aP53My4XyztzqPhSRZxtsce3YxkD3GzOwn/dWpW2ssVPHB0bECQQLFyOtMRR7sl+uEkCQpS2zRyMmsiohLU+wXIVcu+GfwQ9jjL8CZGwS4FZKII2i8I8J2qh7+MCGlVVEe2BRP+NqhrVNOVMitzo2PV53HDa23ud53pTBtJWwtJNnDy4/OUk9sLasLAXp7e4PAblXymyqtuBQzEpWBtRiTSsKHUNsIx9xLXsHowhPkz5I42KCa4ZCUzYkk6k2Wk6zlm/uWQyAPPVZvVFP1iaKN9501auW0VKaFBaF7LCXGiDLGY8mA8NCUdTcwKsPp5cBG2t4lncETasVFPtDpbSi2FCC3fGB6muCq8Uoejul/8jyWRrmpGMdw9llGMtA4Nx+bBVEmAqWDwq9AOhSzPtiyBOLb/k0IywEIoYDtpzxUNeKPQEAQ3H0MOuUGrcxHdZVM7bjiDiWvcLJi+tlltySx8mb2Z4ypA5sc3ZD0vJReiqe5sQ43vQ9O066XuQ/RV/LrvRdBSbmqB5vB9mWknHyV4gMs2x1jWrbDNVe3RtKOj1LdGgGf9W+6uDx8uMBWz4S89aq27ZAIcI6RV+Ezdwq4QNwY6H/nVQbPXdR0Ys5Cfm+R6u8ML946Pc+Fr5ULCT2mTcjBU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
